apiVersion: v1
kind: Pod
metadata:
  name: {pod_prefix}-{container_hash}
  namespace: {namespace}
  labels:
    type: {pod_prefix}
    run_id: '{run_id}'
    instance: {instance_name}
    last_connect: '{last_connect}'
    agent_id: '{agent_id}'

spec:
  restartPolicy: Never
  containers:
  - command: ["sh", "-c"]
    args: [ "{cmd}"]
    image: {image}
    imagePullPolicy: Always
    name: {pod_prefix}-{container_hash}
    volumeMounts:
    - mountPath: /data/nextflow/
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: {claim_name}