"""
    Unison agent API

    API for opensource nextflow runner agent. A federation node  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auto_api_client
from auto_api_client.model.biobank_data_column import BiobankDataColumn
globals()['BiobankDataColumn'] = BiobankDataColumn
from auto_api_client.model.biobank_data_table import BiobankDataTable


class TestBiobankDataTable(unittest.TestCase):
    """BiobankDataTable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBiobankDataTable(self):
        """Test BiobankDataTable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BiobankDataTable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
