"""
    Unison agent API

    API for opensource nextflow runner agent. A federation node  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auto_api_client
from auto_api_client.model.set_cohort_definition_aggregation_request import SetCohortDefinitionAggregationRequest


class TestSetCohortDefinitionAggregationRequest(unittest.TestCase):
    """SetCohortDefinitionAggregationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetCohortDefinitionAggregationRequest(self):
        """Test SetCohortDefinitionAggregationRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetCohortDefinitionAggregationRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
