"""
    Unison agent API

    API for opensource nextflow runner agent. A federation node  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import auto_api_client
from auto_api_client.api.agent_api import AgentApi  # noqa: E501


class TestAgentApi(unittest.TestCase):
    """AgentApi unit test stubs"""

    def setUp(self):
        self.api = AgentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accept_task(self):
        """Test case for accept_task

        """
        pass

    def test_add_run_log_chunk(self):
        """Test case for add_run_log_chunk

        """
        pass

    def test_block_task(self):
        """Test case for block_task

        """
        pass

    def test_export_cdm_values_csv(self):
        """Test case for export_cdm_values_csv

        """
        pass

    def test_export_cdm_vocabulary_csv(self):
        """Test case for export_cdm_vocabulary_csv

        """
        pass

    def test_export_docs_for_specific_biobank(self):
        """Test case for export_docs_for_specific_biobank

        """
        pass

    def test_export_docs_for_specific_biobank_in_csv_format(self):
        """Test case for export_docs_for_specific_biobank_in_csv_format

        """
        pass

    def test_export_mapping_short_for_specific_biobank(self):
        """Test case for export_mapping_short_for_specific_biobank

        """
        pass

    def test_export_mapping_short_for_specific_biobank_json(self):
        """Test case for export_mapping_short_for_specific_biobank_json

        """
        pass

    def test_get_agent_id(self):
        """Test case for get_agent_id

        """
        pass

    def test_get_app_agent_updateprocessitem(self):
        """Test case for get_app_agent_updateprocessitem

        """
        pass

    def test_get_mappings(self):
        """Test case for get_mappings

        """
        pass

    def test_get_next_task(self):
        """Test case for get_next_task

        """
        pass

    def test_get_types_map(self):
        """Test case for get_types_map

        """
        pass

    def test_post_app_agent_addjoblogs(self):
        """Test case for post_app_agent_addjoblogs

        """
        pass

    def test_set_car_status(self):
        """Test case for set_car_status

        """
        pass

    def test_set_cohort_definition_aggregation(self):
        """Test case for set_cohort_definition_aggregation

        """
        pass

    def test_set_error_for_cohort_api_request(self):
        """Test case for set_error_for_cohort_api_request

        """
        pass

    def test_set_installed_pipelines(self):
        """Test case for set_installed_pipelines

        """
        pass

    def test_set_job_state(self):
        """Test case for set_job_state

        """
        pass

    def test_set_kill_result(self):
        """Test case for set_kill_result

        """
        pass

    def test_set_process_logs(self):
        """Test case for set_process_logs

        """
        pass

    def test_set_run_dir(self):
        """Test case for set_run_dir

        """
        pass

    def test_set_run_status(self):
        """Test case for set_run_status

        """
        pass

    def test_set_sql_query_for_cohort_api_request(self):
        """Test case for set_sql_query_for_cohort_api_request

        """
        pass

    def test_set_table_column_freequent_values(self):
        """Test case for set_table_column_freequent_values

        """
        pass

    def test_set_table_column_stats(self):
        """Test case for set_table_column_stats

        """
        pass

    def test_set_table_info(self):
        """Test case for set_table_info

        """
        pass

    def test_set_table_stats(self):
        """Test case for set_table_stats

        """
        pass

    def test_set_tables_list(self):
        """Test case for set_tables_list

        """
        pass

    def test_set_task_error(self):
        """Test case for set_task_error

        """
        pass

    def test_update_process_item(self):
        """Test case for update_process_item

        """
        pass


if __name__ == '__main__':
    unittest.main()
