"""
    Unison agent API

    API for opensource nextflow runner agent. A federation node  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auto_api_client
from auto_api_client.model.set_installed_pipelines_request import SetInstalledPipelinesRequest


class TestSetInstalledPipelinesRequest(unittest.TestCase):
    """SetInstalledPipelinesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetInstalledPipelinesRequest(self):
        """Test SetInstalledPipelinesRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetInstalledPipelinesRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
