"""
    Unison agent API

    API for opensource nextflow runner agent. A federation node  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import auto_api_client
from auto_api_client.api.agent_api import AgentApi  # noqa: E501


class TestAgentApi(unittest.TestCase):
    """AgentApi unit test stubs"""

    def setUp(self):
        self.api = AgentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_next_task(self):
        """Test case for get_next_task

        """
        pass

    def test_get_types_map(self):
        """Test case for get_types_map

        """
        pass

    def test_post_app_agent_addrunlogchunk(self):
        """Test case for post_app_agent_addrunlogchunk

        """
        pass

    def test_post_app_agent_setprocesslogs(self):
        """Test case for post_app_agent_setprocesslogs

        """
        pass

    def test_post_app_agent_setrunstatus(self):
        """Test case for post_app_agent_setrunstatus

        """
        pass

    def test_post_app_agent_updateprocessitem(self):
        """Test case for post_app_agent_updateprocessitem

        """
        pass


if __name__ == '__main__':
    unittest.main()
