"""
    Unison agent API

    API for opensource nextflow runner agent. A federation node  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import auto_api_client
from auto_api_client.model.get_process_logs import GetProcessLogs
from auto_api_client.model.nextflow_run import NextflowRun
globals()['GetProcessLogs'] = GetProcessLogs
globals()['NextflowRun'] = NextflowRun
from auto_api_client.model.types_map import TypesMap


class TestTypesMap(unittest.TestCase):
    """TypesMap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTypesMap(self):
        """Test TypesMap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TypesMap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
