api_version: 1.0
api_url: "http://localhost:8082"
agent_token: "63478ac069b96f79b9d97c9"
work_dir: "/data/nextflow/pipelines"
type: k8s
idle_delay: 5.0
sentry_dsn: "http://5456fe4ea5f29f4220513a965b25ce15@18.185.189.107:9000/3"
log:
  level: 10 # 10 - debug, 50 - critical
  filename: "" #filename or empty for stdout
k8s:
  namespace: "dev"
  master_pod: "nextflow-dev"
  pod_prefix: "unison-worker"
  volume: "ebs-claim-prod-10"

phenoenotypicDb:
  dsn: postgresql+psycopg2://***:***@***:***/***
  schema: Omop
  min_count: 3