version: '3'

services:
  unison-agent:
    image: entsupml/unison-runner:latest
    container_name: ${CONTAINER_NAME:-unison-runner}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      UNISON_API_TOKEN: ${UNISON_API_TOKEN}
      UNISON_DSN: ${UNISON_DSN}
    volumes:
      - ./var:/app/var:delegated

  dqd-omop-5.4:
    container_name: ${CONTAINER_NAME:-unison-agent}-dqd-omop-5.4
    image: entsupml/unison-runner-dqd-omop-5.4
    ports: [8080]
    volumes:
      - ./var:/data:delegated