version: '3'

services:
  unison-agent:
    build:
      context: .
      dockerfile: Resources/docker/Dockerfile
    container_name: ${CONTAINER_NAME:-unison-runner}
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - ./:/app:delegated
      - ./Resources/.kube/:/root/.kube
      - ./Resources/.aws:/root/.aws
      - ./Resources/gcloud/:/root/.config/gcloud
      #- /var/run/docker.sock:/var/run/docker.sock

  filebeat:
    container_name: ${CONTAINER_NAME:-unison-agent}-filebeat
    image: elastic/filebeat:8.10.3
    entrypoint: filebeat -e -strict.perms=false
    user: root
    environment:
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      WORKER_NAME: ${CONTAINER_NAME}
    volumes:
      - ./Resources/docker/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  dqd-omop-5.4:
    container_name: ${CONTAINER_NAME:-unison-agent}-dqd-omop-5.4
    image: entsupml/unison-runner-dqd-omop-5.4
#    build:
#      context: Resources/dqd-omop-5.4/
#      dockerfile: Dockerfile
    ports: [8080]
    volumes:
      - ./var:/data:delegated
      - ./Resources/dqd-omop-5.4/:/app