version: '3'

services:
  unison-agent:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Resources/docker/Dockerfile
    entrypoint: bash -c "cd /app; pip install -r requirements.txt; sleep infinity; echo test"
    volumes:
      - ./:/app:delegated
      - ./Resources/.kube/:/root/.kube
      - ./Resources/.aws:/root/.aws

  filebeat:
    profiles: [ "filebeat" ]

