version: '3'

services:
  unison-agent:
    build:
      context: .
      dockerfile: Resources/docker/Dockerfile
    container_name: unison-agent
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/app:delegated
      - ./Resources/.kube/:/root/.kube
      - ./Resources/.aws:/root/.aws
