version: '3'


services:
  unison-agent:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Resources/docker/Dockerfile
    entrypoint: bash -c "cd /app; pip install -r requirements.txt; sleep infinity; echo test"
    volumes:
      - ./:/app:delegated
      - ./Resources/.kube/:/root/.kube
      - ./Resources/.aws:/root/.aws

  pgsql:
    image: postgres:16.4
    ports:
      - "${EXPORT_PGSQL_PORT}:5432"
    environment:
      POSTGRES_DB: ${EXPORT_PGSQL_DATABASE}
      POSTGRES_USER: ${EXPORT_PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${EXPORT_PGSQL_PASSWORD}
    volumes:
      - ./var/pgsql:/var/lib/postgresql/data