logging.level: warning
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.name: '${WORKER_NAME:}'
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              include_lines: ['^{']
              exclude_lines: [ "^\\s+[\\-`('.|_]" ]  # drop asciiart lines

processors:
  - decode_json_fields:
      fields: ["message", "level"]
      process_array: true
      max_depth: 2
      target: "json"
      overwrite_keys: true
      add_error_key: true

output.elasticsearch:
  allow_older_versions: true
  hosts: ['${ELASTICSEARCH_HOST:}']
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

